apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sitio
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/c/Users/WIN10/Desktop/proyecto-devops/sitio-web
