apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitio-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitio-web
  template:
    metadata:
      labels:
        app: sitio-web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: contenido-web
          mountPath: /usr/share/nginx/html
      volumes:
      - name: contenido-web
        persistentVolumeClaim:
          claimName: pvc-sitio
